### PR TITLE
A session analyzer

### PR DESCRIPTION
**Pull request by margirova**

### CODE REVIEW

**Comment by margirova** [comment]
- found a nice numpy structure, dictionary-like, but preserving the same features of np.arrays
- untested yet

**Comment by ateska** [comment]
Looking good so far. Concept is clearer now.
I would like to think about sessions as matrices: rows are `sessions ids` columns are fixed attributes such as `session_start`, `session_end` and all kinds of aggregations such as number of session objects.
Each session can be also extended with complex types such as lists or dicts (this concept can be added to Time Window as well).

**Comment by margirova** [comment]
- deactivate => close_session
- added "@timestamp_end" as well
Basically sessions now are what you describe: rows with session ids are colums are aggregations and we call them by their names, not by indexes as in timewindow matrix. Moreover, if we take specific column_id , we get the whole matrix (regular numpy) with all session_ids. However, we cannot use anything size unstable like dictionary or lists, numpy is a rigid structure. But nested numpy structures are ok to use

**Comment by ateska** [comment]
Ok - we will have to find out how to approach dictionaries and lists ... both for TWA and SA.
Beside of that, do you want to merge this?

**Comment by margirova** [comment]
For dictionaries and lists we can use pointers to storage, those can list or dictionaries, in some TWA it was implemented.
I will write an example/test and then merge

**Pull request merged**
